server:
  port: 8080
spring:
  application:
    name: gateway
  config:
    import: "nacos:gateway.yaml"
  cloud:
    nacos:
      discovery:
        server-addr: 101.37.202.108:8848
      config:
        server-addr: 101.37.202.108:8848
    gateway:
      discovery:
        locator:
          enabled: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi